# Generated by Django 5.0.3 on 2024-09-26 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clashes',
            name='created_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 9, 53, 2, 713015)),
        ),
    ]
