# Generated by Django 5.0.3 on 2024-09-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='recovery_email_id',
        ),
        migrations.AddField(
            model_name='myuser',
            name='edu_email_id',
            field=models.EmailField(default='abc@nitk.edu.in', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(blank=True, default='abc@gmail.com', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
