# Generated by Django 5.0.3 on 2024-09-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0003_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='edu_email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
