# Generated by Django 5.0.3 on 2024-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0004_alter_myuser_edu_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
