# Generated by Django 5.0.3 on 2024-09-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0005_alter_myuser_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='edu_email_id',
            new_name='eduMailID',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
