# Generated by Django 5.0.3 on 2024-09-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0006_rename_edu_email_id_myuser_edumailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
    ]
